export const membershipPlans = [
  {
    id: 1,
    name: "Daily Pass",
    price: "$8",
    duration: "/day",
    featured: false,
    description: "Perfect for occasional workouts or trying our facilities.",
    features: [
      "Unlimited access for one day",
      "Strength & cardio area",
      "Locker room access",
      "Free drinking water",
    ],
    button: "Get Daily Pass",
  },
  {
    id: 2,
    name: "Monthly Membership",
    price: "$49",
    duration: "/month",
    featured: true,
    description: "Our most popular plan for consistent training and progress.",
    features: [
      "Unlimited gym access",
      "Group fitness classes",
      "Locker room access",
      "Free fitness assessment",
      "Member discounts",
    ],
    button: "Become a Member",
  },
  {
    id: 3,
    name: "Annual Membership",
    price: "$499",
    duration: "/year",
    featured: false,
    description: "Best value for long-term commitment and maximum savings.",
    features: [
      "Everything in Monthly",
      "2 personal training sessions",
      "Priority event access",
      "Exclusive merchandise discount",
      "Save over 15%",
    ],
    button: "Choose Annual Plan",
  },
];
